train:
    dataset: Hi4D
    subject: "football"
    start_frame: 0
    end_frame: 201
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : /scratch/izar/cizinsky/multiply-output/preprocessing/data/football_high_res
    num_sample : 512
    using_SAM: True
    ratio_uncertain: 0.5

valid:
    dataset: "Hi4DVal"
    subject: "football"
    start_frame: 0
    end_frame: 75
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : /scratch/izar/cizinsky/multiply-output/preprocessing/data/football_high_res
    num_sample : -1
    pixel_per_batch: 512
    using_SAM: True

test:
    dataset: "Hi4DTest"
    subject: "football"
    start_frame: 100
    end_frame: 200
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : /scratch/izar/cizinsky/multiply-output/preprocessing/data/football_high_res
    num_sample : 0
    pixel_per_batch: 512
    using_SAM: True